---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: glebedev
  namespace: users
---
apiVersion: v1
kind: Secret
metadata:
  name: sfedonin-token
  namespace: users
  annotations:
    kubernetes.io/service-account.name: glebedev
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-glebedev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: glebedev
  namespace: users
